db.insertfromJS.insertOne({"name":"Sai","rollno":1})
db.insertfromJS.insertOne({"name":"Rahul","rollno":2})
db.insertfromJS.insertOne({"name":"Rajesh","rollno":3})
db.insertfromJS.insertOne({"name":"Vinay","rollno":4})
db.insertfromJS.insertOne({"name":"Manoj","rollno":5})